trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/ecomm-api-svc/

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: e2e-integration-tests

stages:
  - stage: ecomm_api_svc
    displayName: Build and push ecomm api svc cypress test docker image
    dependsOn: []

    jobs:
    - template: ./templates/cypress-test-docker-build-push.yaml
      parameters:
        packageName: ecomm-api-svc
        repositoryName: cypress-ecomm-api-svc
