trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - src/ezpay-payer-portal/

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: e2e-integration-tests

stages:
  - stage: ezpay_payer_portal
    displayName: Build and push ezpay payer portal cypress test docker image
    dependsOn: []

    jobs:
    - template: ./templates/cypress-test-docker-build-push.yaml
      parameters:
        packageName: ezpay-payer-portal
        repositoryName: cypress-ezpay-payer-portal